#!/usr/bin/env bash

# WIP

# Making sure base and base-devel is installed
echo "Installing base and base-devel group"
echo " "
sudo pacman -S base base-devel
echo " "

# Setting up YAY
echo "Setting up YAY helper"
cd ~/.config
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~


# Pull down dotfiles from github

cd ~
mkdir repository
cd repository
git clone git@github.com:jaygoppers/dotfiles.git
git clone git@github.com:jaygoppers/startpages.git
cd ~
mkdir Media
cd Media
git clone git@github.com:jaygoppers/wallpapers.git



